Add token to payments test build.

diff --git a/.gitlab-ci-release.yml b/.gitlab-ci-release.yml
--- a/.gitlab-ci-release.yml
+++ b/.gitlab-ci-release.yml
@@ -128,6 +128,14 @@ build payments black google dev:
   tags:
     - android-xlarge
   script:
+    - export BLACK_TOKEN="$(curl --silent $BLACK_TOKEN_URL)"
+    - echo "API host ${TEST_ENV_DOMAIN}"
+    - echo "API token ${BLACK_TOKEN}"
+    - |
+      if [[ "$BLACK_TOKEN" == *$'\n'* || "$BLACK_TOKEN" == *" "* ]]; then
+        echo "Invalid token: ${BLACK_TOKEN}"
+        exit 1
+      fi
     - >
       ./gradlew openvpn:assembleRelease \
                 assembleBlackGoogleDevRelease \
